### ISSUE TITLE
makedirs error

### ISSUE THREAD

**Issue by cmclaughlin** [ikreymer/certauth#10]
This looks like a nice project, but I'm just checking it out for the first time and can't get it to work...

```
# certauth myrootca.pem --certname "My Test CA"
Traceback (most recent call last):
  File "/tmp/charles/bin/certauth", line 11, in <module>
    sys.exit(main())
  File "/tmp/charles/lib64/python3.6/dist-packages/certauth/certauth.py", line 371, in main
    ca_file_cache = RootCACache(root_cert)
  File "/tmp/charles/lib64/python3.6/dist-packages/certauth/certauth.py", line 317, in __init__
    super(RootCACache, self).__init__(ca_dir)
  File "/tmp/charles/lib64/python3.6/dist-packages/certauth/certauth.py", line 290, in __init__
    os.makedirs(certs_dir)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Same problem using the API:

```
>>> from certauth.certauth import CertificateAuthority
>>> ca = CertificateAuthority('My Custom CA', 'my-ca.pem', cert_cache='/tmp/certs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/charles/lib64/python3.6/dist-packages/certauth/certauth.py", line 54, in __init__
    self.ca_file_cache = RootCACache(ca_file_cache)
  File "/tmp/charles/lib64/python3.6/dist-packages/certauth/certauth.py", line 317, in __init__
    super(RootCACache, self).__init__(ca_dir)
  File "/tmp/charles/lib64/python3.6/dist-packages/certauth/certauth.py", line 290, in __init__
    os.makedirs(certs_dir)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '
```

After downgrading to the 1.1.6 release this problem goes away. I tried going through the git history, but it's not clear where the problem is.

**Comment by ikreymer** [comment]
Ah nice catch, the issue is just that the directory for the root ca is empty.
If you run `certauth ./myrootca.pem --certname "My Test CA"` it will work (makedirs will be called with  `'.'` instead of `''`). Will add a fix.

**Comment by cmclaughlin** [comment]
Awesome... thanks!
